Add custom webhooks
ajayyy/SponsorBlockServer pull request #118
Opened 2020-08-23 18:47 UTC by TAG-Epic

2020-08-23 18:58 UTC, ajayyy requested changes
Looks good. Maybe this stuff can be moved into a separate function to not clog up the vote function.

2020-08-23 18:58 UTC, ajayyy commented on src/routes/voteOnSponsorTime.js
> +                                        "status": userSubmissionCountRow.submissionCount === 0 ? "new" : (isVIP ? "vip" : "normal")
Include self vote here. Maybe move it to a function like `getVoteAuthor()`.

2020-08-23 18:58 UTC, ajayyy commented on src/routes/voteOnSponsorTime.js
> +                            }
Instead of returning, I think it would make more sense if you flipped the if statement.

2020-08-23 18:58 UTC, ajayyy commented on src/routes/voteOnSponsorTime.js
> +                                        "id": UUID,
```suggestion
                                        "UUID": UUID,
```

2020-08-23 18:58 UTC, ajayyy commented on src/routes/voteOnSponsorTime.js
> +                                        "id": submissionInfoRow.videoID,
```suggestion
                                        "videoID": submissionInfoRow.videoID,
```

2020-08-23 18:58 UTC, ajayyy commented on src/routes/voteOnSponsorTime.js
> +                                            "uuid": submissionInfoRow.userID,
```suggestion
                                            "UUID": submissionInfoRow.userID,
```

2020-08-23 18:58 UTC, ajayyy commented on src/routes/voteOnSponsorTime.js
> +                    let isUpvote = incrementAmount > 0
Can you add semi-colons?

2020-08-23 19:00 UTC, Joe-Dowd requested changes

2020-08-23 19:05 UTC, Joe-Dowd commented on src/routes/voteOnSponsorTime.js
> +                                    "Authorization": key,
Maybe make this a Bearer token rather than just the key

2020-08-23 19:09 UTC, Joe-Dowd commented on src/routes/voteOnSponsorTime.js
> +                        err && console.log(err);
logger.error

2020-08-23 20:08 UTC, ajayyy commented on src/routes/voteOnSponsorTime.js
> +                        "isOwnSubmission": isOwnSubmission,
You can remove this duplicate

2020-08-23 20:11 UTC, ajayyy commented on src/routes/voteOnSponsorTime.js
> +                    }
Can you move this into a function like `getVoteAuthor()`?

2020-08-23 20:20 UTC, Joe-Dowd commented on src/routes/voteOnSponsorTime.js
> +            if (config.youtubeAPIKey !== null && (webhookURL !== null || config.webhooks.size !== 0)) {
This will still error if config.webhooks is undefined

2020-08-23 20:23 UTC, Joe-Dowd commented on src/routes/voteOnSponsorTime.js
> +            if (config.youtubeAPIKey !== null && (webhookURL !== null || config.webhooks.size !== 0)) {
and should be config.webhooks.length

2020-08-23 20:23 UTC, Joe-Dowd commented on src/utils/dispatchWebhooks.js
> +    if (webhooks === undefined || webhooks.size === 0) return;
should be webhooks.length

2020-08-23 20:39 UTC, ajayyy commented on src/utils/dispatchWebhooks.js
> +}
Should this be in the webhook utils?

2020-08-23 20:40 UTC, ajayyy commented on src/utils/webhookUtils.js
> +module.exports.getVoteAuthor = getVoteAuthor;
```suggestion
module.exports = {
    getVoteAuthorRaw,
    getVoteAuthor 
}
```

2020-08-24 18:05 UTC, Joe-Dowd requested changes

2020-08-24 18:05 UTC, Joe-Dowd commented on config.json.example
> +    "webhooks": []
add a webhook with a mock endpoint defined in the test code so the new feature is tested

2020-08-24 18:05 UTC, Joe-Dowd commented on src/routes/postSkipSegments.js
> +            } catch (err) {s
random s

2020-08-24 21:11 UTC, ajayyy approved these changes

2020-08-24 21:48 UTC, Joe-Dowd commented
https://github.com/TAG-Epic/SponsorBlockServer/pull/4

2020-08-27 02:41 UTC, ajayyy commented
Could the webhooks be moved to being sent after the server has sent a response code?

2020-08-29 23:26 UTC, merged

2026-09-07 00:40 UTC, edergaelvazquez23-gif reviewed
> `[](url)` @